-- ============================================================
-- STEP 1: Add new columns to assets table
-- ============================================================
ALTER TABLE public.assets
  ADD COLUMN IF NOT EXISTS asset_code TEXT,
  ADD COLUMN IF NOT EXISTS rate_mahasiswa NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS rate_pascasarjana NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS rate_dosen_karyawan NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS rate_kerjasama NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS rate_umum NUMERIC(12,2);

-- ============================================================
-- STEP 2: Insert equipment data from CSV
-- ============================================================
INSERT INTO public.assets (
  name, category, merk, current_condition, sumber, description,
  ketersediaan, status_tindakan, asset_code,
  rate_mahasiswa, rate_pascasarjana, rate_dosen_karyawan, rate_kerjasama, rate_umum
) VALUES
  ('Vital Capacity Meter', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0001', 0, 112500, 150000, 187000, 225000),
  ('Speed Anticipation', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0002', 0, 75000, 100000, 125000, 150000),
  ('Whole Body Reaction', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0003', 0, 75000, 100000, 100000, 150000),
  ('Whole Body Reaction', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0004', 0, 75000, 100000, 100000, 150000),
  ('Standing trunk Flexion', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0005', 0, 37500, 50000, 62500, 75000),
  ('Attachment Selector', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0006', 0, 75000, 100000, 125000, 150000),
  ('Speed anticipation', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0007', 0, 75000, 100000, 125000, 150000),
  ('Jump MD', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0008', 0, 37500, 50000, 62500, 75000),
  ('Digital dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0009', 0, 100000, 125000, 150000, 175000),
  ('Speed anticipation', 'equipment', NULL, 'needs_repair', 'SSFC', 'Lampu nya mati', 'tersedia', 'normal', 'USC-0010', 0, 75000, 100000, 125000, 150000),
  ('Jump DF', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0011', 0, 56250, 75000, 93750, 112500),
  ('Force plate', 'equipment', NULL, 'needs_repair', 'SSFC', 'Harus update driver', 'tersedia', 'normal', 'USC-0012', 0, 37500, 50000, 62500, 75000),
  ('Ergoline', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0013', 0, 100000, 125000, 150000, 175000),
  ('Cosmed', 'equipment', NULL, 'damaged', 'FIKK', NULL, 'tersedia', 'normal', 'USC-0014', 0, 150000, 175000, 200000, 250000),
  ('Side Step', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0015', 0, 75000, 100000, 125000, 150000),
  ('Mirror drawing', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0016', 0, 37500, 50000, 62500, 75000),
  ('CPET', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0017', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0018', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0019', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0020', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0021', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0022', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0023', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0024', 0, 150000, 175000, 200000, 250000),
  ('CPET', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0025', 0, 150000, 175000, 200000, 250000),
  ('Antropometri', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0026', 0, 75000, 100000, 125000, 150000),
  ('Cosmed K4', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0027', 0, 150000, 175000, 200000, 250000),
  ('Cosmed K4', 'equipment', NULL, 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0028', 0, 150000, 175000, 200000, 250000),
  ('Kamera Panasonic', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0029', 0, 100000, 125000, 150000, 175000),
  ('Kamera vicon', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0030', 0, 100000, 125000, 150000, 175000),
  ('Smart speed', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0031', 0, 100000, 125000, 150000, 175000),
  ('Ball medicine', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0032', 0, 18750, 25000, 31250, 37500),
  ('Jump DF', 'equipment', NULL, 'good', 'SSFC', 'Plate cuman 1', 'tersedia', 'normal', 'USC-0033', 0, 56250, 75000, 93750, 112500),
  ('Speed light', 'equipment', NULL, 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0034', 0, 100000, 125000, 150000, 175000),
  ('Skinfold caliper', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0035', 0, 67500, 90000, 112500, 135000),
  ('Sit and reach', 'equipment', NULL, 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0036', 0, 37500, 50000, 62500, 75000),
  ('Back and leg dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0037', 0, 75000, 100000, 125000, 150000),
  ('Back and leg dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0038', 0, 75000, 100000, 125000, 150000),
  ('Back and leg dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0039', 0, 75000, 100000, 125000, 150000),
  ('Back and leg dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0040', 0, 75000, 100000, 125000, 150000),
  ('Grip Strength Dynamometer', 'equipment', 'Takei', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0041', 0, 75000, 100000, 125000, 150000),
  ('Balance Board', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0076', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 2kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0077', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 2.5kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0078', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 5kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0079', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 1.5kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0080', 0, NULL, NULL, NULL, NULL),
  ('Balance Board', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0088', 0, NULL, NULL, NULL, NULL),
  ('Meteran TB', 'equipment', 'Gea Medical', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0089', NULL, NULL, NULL, NULL, NULL),
  ('Balance Board', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0097', 0, NULL, NULL, NULL, NULL),
  ('Battle Rope', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0099', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0102', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0103', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0104', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0105', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'damaged', 'SSFC', 'Mati', 'tersedia', 'normal', 'USC-0106', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'damaged', 'SSFC', 'Mati', 'tersedia', 'normal', 'USC-0107', 0, NULL, NULL, NULL, NULL),
  ('Ergocycle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0108', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0109', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0110', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0111', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0112', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'damaged', 'SSFC', 'Karpet tidak ada', 'tersedia', 'normal', 'USC-0113', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0114', 0, NULL, NULL, NULL, NULL),
  ('Treadmill', 'equipment', 'Technogym', 'damaged', 'SSFC', 'Karpet tidak ada', 'tersedia', 'normal', 'USC-0115', 0, NULL, NULL, NULL, NULL),
  ('Crossover 700', 'equipment', 'Technogym', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0116', 0, NULL, NULL, NULL, NULL),
  ('Crossover 700', 'equipment', 'Technogym', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0117', 0, NULL, NULL, NULL, NULL),
  ('Excite', 'equipment', 'Technogym', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0118', 0, NULL, NULL, NULL, NULL),
  ('Bike race', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0119', 0, NULL, NULL, NULL, NULL),
  ('Pulley', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0120', 0, NULL, NULL, NULL, NULL),
  ('Lat machine', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0121', 0, NULL, NULL, NULL, NULL),
  ('Leg Press', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Perlu dirakit', 'tersedia', 'normal', 'USC-0122', 0, NULL, NULL, NULL, NULL),
  ('Multi Power', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0123', 0, NULL, NULL, NULL, NULL),
  ('Leg Curl', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Belum dirakit', 'tersedia', 'normal', 'USC-0124', 0, NULL, NULL, NULL, NULL),
  ('Multi hip', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0125', 0, NULL, NULL, NULL, NULL),
  ('bod pod', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Tinggal di rakit', 'tersedia', 'normal', 'USC-0126', 0, NULL, NULL, NULL, NULL),
  ('Chest Press', 'equipment', 'Technogym', 'needs_repair', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0127', 0, NULL, NULL, NULL, NULL),
  ('Chest Incline', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Belum dirakit', 'tersedia', 'normal', 'USC-0128', 0, NULL, NULL, NULL, NULL),
  ('Butterfly', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0129', 0, NULL, NULL, NULL, NULL),
  ('Multi Hip', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0130', 0, NULL, NULL, NULL, NULL),
  ('Arm Curl', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0131', 0, NULL, NULL, NULL, NULL),
  ('Shoulder Press', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0132', 0, NULL, NULL, NULL, NULL),
  ('Leg Curl', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0133', 0, NULL, NULL, NULL, NULL),
  ('Glute', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0134', 0, NULL, NULL, NULL, NULL),
  ('Arm Extension', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Pegangan kiri hilang', 'tersedia', 'normal', 'USC-0135', 0, NULL, NULL, NULL, NULL),
  ('Feed back point offline', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Tidak ada kabel power', 'tersedia', 'normal', 'USC-0136', 0, NULL, NULL, NULL, NULL),
  ('Lower Back', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0137', 0, NULL, NULL, NULL, NULL),
  ('Adductor', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0138', 0, NULL, NULL, NULL, NULL),
  ('Chest Incline', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0139', 0, NULL, NULL, NULL, NULL),
  ('Pulldown', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0142', 0, NULL, NULL, NULL, NULL),
  ('Abductor', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0143', 0, NULL, NULL, NULL, NULL),
  ('Upper Back', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0144', 0, NULL, NULL, NULL, NULL),
  ('Delts Machine', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0145', 0, NULL, NULL, NULL, NULL),
  ('Abdominal Crunch', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0146', 0, NULL, NULL, NULL, NULL),
  ('Vertical Traction', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0147', 0, NULL, NULL, NULL, NULL),
  ('Pulley', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0148', 0, NULL, NULL, NULL, NULL),
  ('Rotary Calf', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0149', 0, NULL, NULL, NULL, NULL),
  ('Chest Press', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0150', 0, NULL, NULL, NULL, NULL),
  ('Rotary Torso', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0151', 0, NULL, NULL, NULL, NULL),
  ('Pectoral', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0152', 0, NULL, NULL, NULL, NULL),
  ('Low Row', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0153', 0, NULL, NULL, NULL, NULL),
  ('Total Abdominal', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0154', 0, NULL, NULL, NULL, NULL),
  ('Lat Machine', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0155', 0, NULL, NULL, NULL, NULL),
  ('Pull Up', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0156', 0, NULL, NULL, NULL, NULL),
  ('Leg Press', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0157', 0, NULL, NULL, NULL, NULL),
  ('Ercolina Radiant', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0158', 0, NULL, NULL, NULL, NULL),
  ('Cable Jungle', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0159', 0, NULL, NULL, NULL, NULL),
  ('Flexibility Anterior', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0160', 0, NULL, NULL, NULL, NULL),
  ('Kinesis', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Tidak ada kunci pemberat', 'tersedia', 'normal', 'USC-0201', 0, NULL, NULL, NULL, NULL),
  ('Kinesis', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0202', 0, NULL, NULL, NULL, NULL),
  ('Indoor Rowing', 'equipment', 'Concept 2', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0203', 0, NULL, NULL, NULL, NULL),
  ('Indoor Rowing', 'equipment', 'Concept 2', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0204', 0, NULL, NULL, NULL, NULL),
  ('Kinesis', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0205', 0, NULL, NULL, NULL, NULL),
  ('Kinesis', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0206', 0, NULL, NULL, NULL, NULL),
  ('Flexability Posterior', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0207', 0, NULL, NULL, NULL, NULL),
  ('Multi Power', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0208', 0, NULL, NULL, NULL, NULL),
  ('Multi Power', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0209', 0, NULL, NULL, NULL, NULL),
  ('Bench', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0210', 0, NULL, NULL, NULL, NULL),
  ('Bench Press', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0211', 0, NULL, NULL, NULL, NULL),
  ('Shoulder Bench', 'equipment', 'Technogym', 'needs_repair', 'SSFC', 'Penahan beban kropos', 'tersedia', 'normal', 'USC-0212', 0, NULL, NULL, NULL, NULL),
  ('Bench Press', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0213', 0, NULL, NULL, NULL, NULL),
  ('Sit Up Bench', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0214', 0, NULL, NULL, NULL, NULL),
  ('Sit Up Bench', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0215', 0, NULL, NULL, NULL, NULL),
  ('Dumbel Rack', 'equipment', NULL, 'needs_repair', 'SSFC', 'Berkarat', 'tersedia', 'normal', 'USC-0216', 0, NULL, NULL, NULL, NULL),
  ('Indoor Rowing', 'equipment', 'Concept 2', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0217', 0, NULL, NULL, NULL, NULL),
  ('EDGE Air Bike', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0218', 0, NULL, NULL, NULL, NULL),
  ('EDGE Air Bike', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0219', 0, NULL, NULL, NULL, NULL),
  ('Dumbbell Rack 3 Tier', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0222', 0, NULL, NULL, NULL, NULL),
  ('Dumbbell Rack 4 Tier', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0223', 0, NULL, NULL, NULL, NULL),
  ('Dumbbell Rack 5 Tier', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0224', 0, NULL, NULL, NULL, NULL),
  ('Plate & Bar Tree', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0225', 0, NULL, NULL, NULL, NULL),
  ('Elite 2D Squat Rack', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0226', 0, NULL, NULL, NULL, NULL),
  ('Edge - SID Bench', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0227', 0, NULL, NULL, NULL, NULL),
  ('Elite 2D Squat Rack', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0228', 0, NULL, NULL, NULL, NULL),
  ('Edge - SID Bench', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0229', 0, NULL, NULL, NULL, NULL),
  ('Elite 2D Squat Rack', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0230', 0, NULL, NULL, NULL, NULL),
  ('Edge - SID Bench', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0231', 0, NULL, NULL, NULL, NULL),
  ('Power Slide', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0232', 0, NULL, NULL, NULL, NULL),
  ('Wooden Box', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0234', 0, NULL, NULL, NULL, NULL),
  ('Plate Rack', 'equipment', 'Technogym', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0235', 0, NULL, NULL, NULL, NULL),
  ('Plyosoft Box', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0237', 0, NULL, NULL, NULL, NULL),
  ('VIPR 6KG', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0238', 0, NULL, NULL, NULL, NULL),
  ('Bosu Balance Ball', 'equipment', 'SVRG', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0239', 0, NULL, NULL, NULL, NULL),
  ('Bosu Balance Ball', 'equipment', 'Livepro', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0240', 0, NULL, NULL, NULL, NULL),
  ('Agility Leader', 'equipment', 'SVRG', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0241', 0, NULL, NULL, NULL, NULL),
  ('Agility Leader', 'equipment', 'SVRG', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0242', 0, NULL, NULL, NULL, NULL),
  ('Plyosoft Box', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0243', 0, NULL, NULL, NULL, NULL),
  ('Wooden Box', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0244', 0, NULL, NULL, NULL, NULL),
  ('Equalizer', 'equipment', 'Edge', 'good', 'DBON', '4 pc', 'tersedia', 'normal', 'USC-0245', 0, NULL, NULL, NULL, NULL),
  ('Plate & Bar Tree', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0248', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 32KG', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0249', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 28KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0250', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 24KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0251', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 22KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0252', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 20KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0253', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 16KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0254', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 12KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0255', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 10KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0256', 0, NULL, NULL, NULL, NULL),
  ('Elite Hollow Kettlebell 8KG', 'equipment', NULL, 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0257', 0, NULL, NULL, NULL, NULL),
  ('Abductor', 'equipment', 'Technogym', 'damaged', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0258', 0, NULL, NULL, NULL, NULL),
  ('Stadiometer', 'equipment', 'TTM', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0259', 0, NULL, NULL, NULL, NULL),
  ('Lifting Platform', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0262', 0, NULL, NULL, NULL, NULL),
  ('Junior Bar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0263', 0, NULL, NULL, NULL, NULL),
  ('Women Warza Bar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0264', 0, NULL, NULL, NULL, NULL),
  ('Edge RZ Garuda Bar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0265', 0, NULL, NULL, NULL, NULL),
  ('Livepro Eco Black Plate 5kg', 'equipment', 'Livepro', 'good', 'DBON', '2 pairs lt. 1; 1 pairs lt. 2', 'tersedia', 'normal', 'USC-0266', 0, NULL, NULL, NULL, NULL),
  ('Livepro Eco Black Plate 10kg', 'equipment', 'Livepro', 'good', 'DBON', '2 pairs', 'tersedia', 'normal', 'USC-0267', 0, NULL, NULL, NULL, NULL),
  ('Livepro Eco Black Plate 15kg', 'equipment', 'Livepro', 'good', 'DBON', '2 pairs', 'tersedia', 'normal', 'USC-0268', 0, NULL, NULL, NULL, NULL),
  ('Livepro Eco Black Plate 20kg', 'equipment', 'Livepro', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0269', 0, NULL, NULL, NULL, NULL),
  ('Trolley', 'equipment', 'Krisbow', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0270', 0, NULL, NULL, NULL, NULL),
  ('Junior Bar', 'equipment', 'Edge', 'good', 'DBON', '2 pcs', 'tersedia', 'normal', 'USC-0271', 0, NULL, NULL, NULL, NULL),
  ('Women Warza Bar', 'equipment', 'Edge', 'good', 'DBON', '2 pcs', 'tersedia', 'normal', 'USC-0272', 0, NULL, NULL, NULL, NULL),
  ('Edge RZ Garuda Bar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0273', 0, NULL, NULL, NULL, NULL),
  ('Bosu Balance Ball', 'equipment', 'SVRG', 'good', 'SSFC', NULL, 'tersedia', 'normal', 'USC-0274', 0, NULL, NULL, NULL, NULL),
  ('VIPR 8kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0275', 0, NULL, NULL, NULL, NULL),
  ('VIPR 4kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0276', 0, NULL, NULL, NULL, NULL),
  ('Hexabar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0277', 0, NULL, NULL, NULL, NULL),
  ('EZ Curl Bar', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0278', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 0.5kg', 'equipment', 'Edge', 'good', 'DBON', '3 pairs', 'tersedia', 'normal', 'USC-0279', 0, NULL, NULL, NULL, NULL),
  ('Change Plate 1kg', 'equipment', 'Edge', 'good', 'DBON', NULL, 'tersedia', 'normal', 'USC-0280', 0, NULL, NULL, NULL, NULL),
  ('Push Pull Dynamometer', 'equipment', 'TTM', 'good', NULL, 'Pindah Lt 4', 'digunakan', 'normal', 'USC-0281', NULL, 37500, 50000, 62500, 75000),
  ('Push Pull Dynamometer', 'equipment', 'TTM', 'good', NULL, 'Pindah Lt 4', 'tersedia', 'normal', 'USC-0282', NULL, 37500, 50000, 62500, 75000),
  ('Push Pull Dynamometer', 'equipment', 'TTM', 'good', NULL, 'Pindah Lt 4', 'tersedia', 'normal', 'USC-0283', NULL, 37500, 50000, 62500, 75000),
  ('Push Pull Dynamometer', 'equipment', 'TTM', 'good', NULL, 'Pindah Lt 4', 'tersedia', 'normal', 'USC-0284', NULL, 37500, 50000, 62500, 75000),
  ('Push Pull Dynamometer', 'equipment', 'TTM', 'needs_repair', NULL, 'Pindah Lt 4', 'tersedia', 'normal', 'USC-0285', NULL, 37500, 50000, 62500, 75000),
  ('Timbangan BB', 'equipment', 'MI (Gea Medical)', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0286', NULL, NULL, NULL, NULL, NULL),
  ('Meteran TB', 'equipment', 'Gea Medical', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0287', NULL, NULL, NULL, NULL, NULL),
  ('Timbangan BB', 'equipment', 'MI (Gea Medical)', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0288', NULL, NULL, NULL, NULL, NULL),
  ('Meteran TB', 'equipment', 'Gea Medical', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0289', NULL, NULL, NULL, NULL, NULL),
  ('Meteran TB', 'equipment', 'Gea Medical', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0290', NULL, NULL, NULL, NULL, NULL),
  ('Meteran Roll', 'equipment', 'Krisbow', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0293', NULL, 40000, 40000, NULL, NULL),
  ('Meteran Roll', 'equipment', 'Krisbow', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0294', NULL, 40000, 40000, NULL, NULL),
  ('Cone', 'equipment', NULL, 'good', NULL, '1 set (10 cone)', 'tersedia', 'normal', 'USC-300', 0, 0, 10000, 0, 0),
  ('Sound JBL', 'equipment', 'JBL', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0291', NULL, NULL, NULL, NULL, NULL),
  ('Mix Wireless Microphone System', 'equipment', 'JBL', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0295', NULL, NULL, NULL, NULL, NULL),
  ('Matras', 'equipment', NULL, 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0296', NULL, NULL, NULL, NULL, NULL),
  ('Body Scale', 'equipment', NULL, 'good', NULL, NULL, 'tersedia', 'normal', 'USC-03001', NULL, NULL, NULL, NULL, NULL),
  ('Marker', 'equipment', NULL, 'good', NULL, NULL, 'tersedia', 'normal', 'USC-03002', NULL, NULL, NULL, NULL, NULL),
  ('Tensi', 'equipment', 'omron', 'good', NULL, NULL, 'tersedia', 'normal', 'USC-0303', NULL, 25000, 25000, NULL, 35000),
  ('Polar Verity', 'equipment', NULL, 'good', NULL, 'harga per polar', 'tersedia', 'normal', 'USC-0304', NULL, 35000, 35000, NULL, 45000),
  ('Body Scale', 'equipment', 'OnPoint', 'good', 'PUI Keolahragaan', NULL, 'tersedia', 'normal', 'USC-305', NULL, NULL, NULL, NULL, NULL);
